name: CI

on:
  push: {}

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v1      

    - name: Prettify code
      run: |
      prettier './**/*.{ts,tsx}' --parser typescript --check